---
title: "Tensorflow workflow"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
library(tensorflow)
library(ggplot2)
library(tfprobability)
library(tidyverse)
library(gridExtra) #for grid.arrange function
library(keras) #need keras or else will not run



#tfp distributions
tfd <- tfp$distributions

#tensorflow eager
tf$compat$v1$enable_eager_execution()
```


```{r}
# normal distribution
n = tfd$Normal(loc = 0, scale = 1)
n

# draw 1 sample
n$sample()

# draw multiple samples
n$sample(3L)

# evaluate a log prob
n$log_prob(value = 0)
n$log_prob(array(0))
n$log_prob(matrix(c(0, 1, -1 , 2), byrow = TRUE, nrow = 2))

# evaluate multiple log prob
n$log_prob(value = c(0, 2, 4))

# bernoulli distribution
b = tfd$Bernoulli(probs = 0.7)

b$sample(8L)

b$log_prob(c(1, 0, 1, 0))

# multivariate normal distribution with diagnonal covariance
nd = tfd$MultivariateNormalDiag(loc = c(0, 1), scale_diag = c(1, 1))
nd

# sampling
nd$sample()

nd$sample(5L)

# log_prob
nd$log_prob(c(0,0))
nd$log_prob(matrix(c(0., 0., 1., 1., 2., 2.), nrow = 3, byrow = TRUE))

nd$log_prob(matrix(0.))

nd$log_prob(matrix(c(0, 1, 2))) # shape (3,)

# multivariate normal distribution with full covariance
ndf = tfd$MultivariateNormalFullCovariance(loc = c(0, 5), covariance_matrix = matrix(c(1, 0.7, 0.7, 1), nrow = 2))

data = ndf$sample(200L)
data = as.matrix(data)
colnames(data) <- c("x", "y")

data = as_tibble(data)

ggplot() +
  geom_point(data = data, aes(x = x, y = y), color = "blue", alpha = 0.4)

# multiple Bernoulli distributions
b3 = tfd$Bernoulli(probs = c(0.3, 0.5, 0.7))
b3

b3$sample()
b3$sample(6L)

b3$prob(c(1, 1, 0))

b3$prob(array(1))

b3$prob(matrix(c(0, 1), nrow = 2))

b3$prob(c(0, 1))

b3_joint = tfd$Independent(b3, reinterpreted_batch_ndims = 1L)
b3_joint

b3_joint$prob(c(1,1,0))

tf$reduce_prod(b3$prob(c(1,1,0)))

# Batches of Multivariate Distributions
nd_batch = tfd$MultivariateNormalFullCovariance(
  loc = list(c(0., 0.), c(1., 1.), c(2., 2.)), 
  covariance_matrix = list(
    matrix(c(1., .1, .1, 1.), ncol = 2), 
    matrix(c(1., .3, .3, 1.), ncol = 2),
    matrix(c(1., .5, .5, 1.), ncol = 2)))


```

```{r}
# One Poisson Scalar Batch
pb1 = tfd$Poisson(rate = 1.)
pb1

# Three Poissons
pb3 = tfd$Poisson(rate = c(1, 10, 100))
pb3
pb3$log_prob(matrix(c(1, 10, 100, 100, 10, 1), nrow = 2, byrow = TRUE)) # sample_shape is [2]

# sample_shape is [1, 1, 2]
pb3$log_prob(array(c(1, 10, 100, 100, 10, 1), dim = c(1,1,2,3))) 

pb3$log_prob(array(10))

pb3$log_prob(array(c(1, 10, 100, 1000), dim = c(2,2,1)))

# Two-by-three Poissons
pb23 = tfd$Poisson(rate = matrix(c(1, 10, 100, 2, 20, 200), byrow = TRUE, nrow = 2))
pb23

pb23$sample(array(c(3L, 4L, 5L)))

pb23$log_prob(1)

# Exactly equivalent to above, demonstrating the scalar special case.
pb23$log_prob(array(1))

# Another way to write the same thing. No broadcasting.
pb23$log_prob(matrix(rep(x = 1, 6), nrow = 2))

# Input is [1, 3] broadcast to [2, 3].
pb23$log_prob(matrix(c(1, 10, 100), nrow = 1))

# Equivalent to above. No broadcasting.
pb23$log_prob(matrix(c(1, 10, 100, 1, 10, 100), nrow = 2, byrow = TRUE))

# No broadcasting.
pb23$log_prob(matrix(c(1, 1, 1, 2, 2, 2), nrow = 2, byrow = TRUE))

# Equivalent to above. Input shape [2, 1] broadcast to [2, 3].
pb23$log_prob(matrix(c(1, 2), nrow = 2, byrow = TRUE))


# One Poisson vector batch
pv = tfd$Poisson(rate = array(1))
pv

# One Poisson extended batch
peb = tfd$Poisson(rate = matrix(1.))
peb
peb$sample(array(c(3L,4L,5L)))

# Standard Normal
n = tfd$Normal(loc = 0, scale = 1)
n

# Standard Vector Batch
nv = tfd$Normal(loc = array(0), scale = 1)
nv

# Different Locs
n4l = tfd$Normal(loc = array(c(0, 1, 2, 3)), scale = 1)
n4l

# Broadcasting Scale
nbc = tfd$Normal(loc = array(c(0, 1, 2, 3)), scale = matrix(c(1, 5), nrow = 2))
nbc

# Long way 
ln = tfd$Normal(loc = list(c(0, 1, 2, 3), c(0, 1, 2, 3)), scale = list(c(1,1,1,1),c(5,5,5,5)))
ln
```

```{r}
# One Multinomial
nom1 = tfd$Multinomial(total_count = 100, probs = c(0.5, 0.4, 0.1))
nom1

nom1$sample(c(1L,5L))

# Two Multinomials Same Probs
nom2 = tfd$Multinomial(total_count = c(100, 1000), probs = c(0.5, 0.4, 0.1))
nom2

nom2$sample(c(1L, 5L))

# Two Multinomials Same Counts
nom3 = tfd$Multinomial(total_count = 100L, probs = list(c(0.5, 0.4, 0.1), c(0.1, 0.2, 0.7)))
nom3

nom3$sample(c(1L, 5L))

# Two Multinomials Different Everything
nom4 = tfd$Multinomial(total_count = c(100, 1000),
                       probs = list(c(0.5, 0.4, 0.1), c(0.1, 0.2, 0.7)))
nom4

nom4$sample(c(1L, 5L))

# 2 3-dimensional Multivariate Normal Distribution
tmn = tfd$MultivariateNormalDiag(
  loc = c(1, 2, 3), 
  scale_identity_multiplier = c(1, 2))

tmn

tmn$log_prob(list(matrix(c(1, 2, 3), nrow = 1), matrix(c(3, 4, 5), nrow = 1)))

# 6 Dimension Multinomial
six_multinomial = tfd$Multinomial(total_count = 1000, probs = c(0.3, 0.25, 0.2, 0.15, 0.08, 0.02))

six_multinomial


transformed_multinomial = tfd$TransformedDistribution(distribution = six_multinomial, bijector = tfb_reshape(event_shape_out = c(2, 3)))

transformed_multinomial

six_multinomial$log_prob(c(500, 100, 100, 150, 100, 50))

transformed_multinomial$log_prob(list(c(500, 100, 100), c(150, 100, 50)))

# Two by five Bernoulli
two_by_five_bern = tfd$Bernoulli(probs = list(c(.05, .1, .15, .2, .25),
                                              c(.3, .35, .4, .45, .5)))
two_by_five_bern

pattern = list(c(1., 0., 0., 1., 0.), c(0., 0., 1., 1., 1.))

two_by_five_bern$log_prob(pattern)


two_sets_of_five = tfd$Independent(distribution = two_by_five_bern, 
                                   reinterpreted_batch_ndims = 1L)
two_sets_of_five
two_sets_of_five$log_prob(pattern)

one_set_of_two_by_five = tfd$Independent(distribution = two_by_five_bern, 
                                   reinterpreted_batch_ndims = 2L)
one_set_of_two_by_five

one_set_of_two_by_five$log_prob(pattern)
```
```{r}

```

